### PR TITLE
MOBILE-206 | Fix 'Save Changes' Button in Edit Profile Screen

### PR DESCRIPTION
**Pull request by Jermainelr**
Screenshot_20240602_134222
Screenshot_20240602_134239

### CODE REVIEW

**Review by cristhianescobar — APPROVED** [review]
LGTM, @Jermainelr can you take a look at the failed UI test on this PR?

**Comment by newmskywalker** [comment]
> LGTM, @Jermainelr can you take a look at the failed UI test on this PR?

I think we just need to record new snapshots. @Jermainelr let me know if you need help!

**Comment by newmskywalker** [comment]
I recorded them and pushed a commit to this PR. The command to do it is `./gradlew recordPaparazziDebug`
Just make sure git lfs is installed and enabled for this repo
https://github.com/cashapp/paparazzi?tab=readme-ov-file#git-lfs

**Comment by cristhianescobar** [comment]
> I recorded them and pushed a commit to this PR. The command to do it is `./gradlew recordPaparazziDebug` Just make sure git lfs is installed and enabled for this repo https://github.com/cashapp/paparazzi?tab=readme-ov-file#git-lfs

Might be a good idea to add the commands to the read me

**Pull request merged**
