### PR TITLE
Build debug apk on development push

### PR DESCRIPTION
**Pull request by newmskywalker**
Deploying the debug apk to firebase distribution on push to the development branch.

Considered doing it for every PR, but not sure how useful that would be

### CODE REVIEW

**Review by andymiller813 — APPROVED** [review]
Awesome!

**Comment by andymiller813** [comment]
> Deploying the debug apk to firebase distribution on push to the development branch.
> 
> Considered doing it for every PR, but not sure how useful that would be

If we do it on every PR we would make sure that this step doesn't fail after merge

**Review by cristhianescobar — APPROVED** [review]
Very niceeeee! 💯  👍🏼

**Comment by newmskywalker** [comment]
> > Deploying the debug apk to firebase distribution on push to the development branch.
> 
> > 
> 
> > Considered doing it for every PR, but not sure how useful that would be
> 
> 
> 
> If we do it on every PR we would make sure that this step doesn't fail after merge 

That's a good call out. I'm adding another check to build and run the test suite on every PR, so hopefully we'll be able to catch broken builds there. If we do still run into issues with broken builds after merge, I can turn this on for every PR

**Pull request merged**
